[2024-11-06T18:15:50.169+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T18:15:50.175+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch_pipeline.fetch_rocket_data manual__2024-11-06T11:15:45.250198+00:00 [queued]>
[2024-11-06T18:15:50.178+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch_pipeline.fetch_rocket_data manual__2024-11-06T11:15:45.250198+00:00 [queued]>
[2024-11-06T18:15:50.178+0700] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-11-06T18:15:50.186+0700] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): fetch_rocket_data> on 2024-11-06 11:15:45.250198+00:00
[2024-11-06T18:15:50.188+0700] {standard_task_runner.py:72} INFO - Started process 3591 to run task
[2024-11-06T18:15:50.190+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'rocket_launch_pipeline', 'fetch_rocket_data', 'manual__2024-11-06T11:15:45.250198+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpok25wst0']
[2024-11-06T18:15:50.190+0700] {standard_task_runner.py:105} INFO - Job 7: Subtask fetch_rocket_data
[2024-11-06T18:15:50.220+0700] {task_command.py:467} INFO - Running <TaskInstance: rocket_launch_pipeline.fetch_rocket_data manual__2024-11-06T11:15:45.250198+00:00 [running]> on host fawzan-HP-Pavilion-x360-2-in-1-Laptop-14-ek1xxx
[2024-11-06T18:15:50.261+0700] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='rocket_launch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_rocket_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T11:15:45.250198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T11:15:45.250198+00:00'
[2024-11-06T18:15:50.261+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-06T18:15:50.262+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-06T18:15:50.262+0700] {logging_mixin.py:190} INFO - Current task name:fetch_rocket_data state:running start_date:2024-11-06 11:15:50.175439+00:00
[2024-11-06T18:15:50.262+0700] {logging_mixin.py:190} INFO - Dag name:rocket_launch_pipeline and current dag run status:running
[2024-11-06T18:15:50.262+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T18:15:50.262+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-06T18:15:50.262+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -L -o /tmp/launches.json https://ll.thespacedevs.com/2.2.0/launch/upcoming']
[2024-11-06T18:15:50.266+0700] {subprocess.py:86} INFO - Output:
[2024-11-06T18:15:50.270+0700] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-11-06T18:15:50.270+0700] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-11-06T18:15:50.428+0700] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2024-11-06T18:15:50.430+0700] {subprocess.py:93} INFO - curl: (60) SSL: no alternative certificate subject name matches target host name 'll.thespacedevs.com'
[2024-11-06T18:15:50.431+0700] {subprocess.py:93} INFO - More details here: https://curl.se/docs/sslcerts.html
[2024-11-06T18:15:50.431+0700] {subprocess.py:93} INFO - 
[2024-11-06T18:15:50.431+0700] {subprocess.py:93} INFO - curl failed to verify the legitimacy of the server and therefore could not
[2024-11-06T18:15:50.432+0700] {subprocess.py:93} INFO - establish a secure connection to it. To learn more about this situation and
[2024-11-06T18:15:50.432+0700] {subprocess.py:93} INFO - how to fix it, please visit the web page mentioned above.
[2024-11-06T18:15:50.433+0700] {subprocess.py:97} INFO - Command exited with return code 60
[2024-11-06T18:15:50.446+0700] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 60.
[2024-11-06T18:15:50.452+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-06T18:15:50.453+0700] {logging_mixin.py:190} INFO - Task start:2024-11-06 11:15:50.175439+00:00 end:2024-11-06 11:15:50.452460+00:00 duration:0.277021
[2024-11-06T18:15:50.453+0700] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): fetch_rocket_data> dag:<DAG: rocket_launch_pipeline> dagrun:<DagRun rocket_launch_pipeline @ 2024-11-06 11:15:45.250198+00:00: manual__2024-11-06T11:15:45.250198+00:00, state:running, queued_at: 2024-11-06 11:15:45.271017+00:00. externally triggered: True>
[2024-11-06T18:15:50.453+0700] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 60.
[2024-11-06T18:15:50.453+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=rocket_launch_pipeline, task_id=fetch_rocket_data, run_id=manual__2024-11-06T11:15:45.250198+00:00, execution_date=20241106T111545, start_date=20241106T111550, end_date=20241106T111550
[2024-11-06T18:15:50.469+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T18:15:50.469+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task fetch_rocket_data (Bash command failed. The command returned a non-zero exit code 60.; 3591)
Traceback (most recent call last):
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 60.
[2024-11-06T18:15:50.483+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-06T18:15:50.501+0700] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T18:15:50.502+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
